CREATE TABLE `pollitos_de_hierro`.`pdh_kid` (
  `pdh_kid_id` INT NOT NULL,
  `pdh_kid_code` TEXT NOT NULL,
  `pdh_kid_name` TEXT NOT NULL,
  `pdh_kid_surname` TEXT NULL,
  `pdh_kid_age` INT NULL,
  `pdh_kid_birth_day` TIMESTAMP NULL,
  `pdh_kid_tshirt_size` INT NULL,
  `pdh_kid_pants_size` INT NULL,
  `pdh_kid_footware_size` DOUBLE NULL,
  `pdh_kid_diaper_size` INT NULL,
  `pdh_kid_diagnose` VARCHAR(45) NULL,
  `pdh_kid_setback` TINYINT(1) NULL,
  `pdh_kid_current_diagnose` VARCHAR(45) NULL,
  `pdh_kid_attached_epicrisis` TINYINT(1) NULL,
  `pdh_kid_headquarters` INT NULL,
  `pdh_kid_geolocation` INT NULL,
  `pdh_kid_number_of_siblings` INT NULL,
  `pdh_kid_last_basket_received` VARCHAR(45) NULL,
  `pdh_kid_number_of_people_living_in_house` INT NULL,
  `pdh_kid_created_by` INT NULL,
  `pdh_kid_updated_by` INT NULL,
  `pdh_kid_created_date` TIMESTAMP NULL,
  `pdh_kid_updated_date` TIMESTAMP NULL,
  PRIMARY KEY (`pdh_kid_id`));
