PrimeFaces.locales["pt"] = {
    closeText: "Remover",
    prevText: "Anterior",
    nextText: "Seguinte",
    monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
    monthNamesShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "dez"],
    dayNames: ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"],
    dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
    dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
    weekHeader: "Semana",
    firstDay: 0,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: "",
    timeOnlyTitle: "Só o tempo",
    timeText: "Tempo",
    hourText: "Tempo",
    minuteText: "Minuto",
    secondText: "Segundo",
    currentText: "Data Atual",
    ampm: false,
    month: "Mês",
    week: "Semana",
    day: "Dia",
    allDayText : "Todo o dia"
};