PrimeFaces.locales["zh"] = {
    closeText: "Supprimer",
    prevText: "Précédent",
    nextText: "Suivant",
    monthNames: ["Janvier", "Février", "Mars", "Avril", "mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
    monthNamesShort: ["Jan", "Février", "Mar", "avril", "mai", "Jun", "Juillet", "Ago", "septembre", "Octobre", "Novembre", "Décembre"],
    dayNames: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
    dayNamesShort: ["Sun", "Mon", "mer", "mer", "Jeu", "Ven", "Sat"],
    dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
    weekHeader: "Semaine",
    firstDay: 0,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: "",
    timeOnlyTitle: "Seul le temps",
    timeText: "Time",
    hourText: "Time",
    minuteText: "Minute",
    secondText: "Second",
    currentText: "Date actuelle",
    ampm: false,
    month: "Mois",
    week: "Semaine",
    day: "Jour",
    allDayText : "Toute la journée"
};